image: "python:3.10"

# We test combinations that cover the following scenarios:
#
# - Minimum and latest version of dependencies (e.g. Python).
# - System-wide installation with CMake and direct source usage.

test-min-cmake:
  image: "python:3.7"
  script:
    - apt-get update -qq && apt-get install -y -qq cmake
    - pip install -r test-requirements.txt
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PATH=/usr/local ..
    - make
    - make install

    # Run tests from a separate, empty folder to make sure folders from the
    # build our source folders are not picked up as Python modules.
    - mkdir empty
    - cd empty
    # but include the directory for files which are not installed
    # inside a canonical python import path
    - export PYTHONPATH="/usr/local/share/pology:$PYTHONPATH"

    - pytest ../../tests

coverage:
  script:
    - pip install -r test-requirements.txt
    - export PATH="$(pwd)/bin:$PATH"
    - export PYTHONPATH="$(pwd):$PYTHONPATH"
    - pytest --cov=pology --cov=scripts --cov=sieve --cov-report term --cov-report xml:coverage.xml tests/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
