<?php
/*
Expects following variables to be defined:

  $page_title: the title of the page (HTML <title>)

*/

//mb_internal_encoding("UTF-8");
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title><?php echo $page_title?></title>
<link rel="stylesheet" href="main.css" type="text/css">
</head>
<body>

<?php
?>
